[repository]
name = "hyprtoplr"
authors = ["subez"]
commit_pins = [
  # ["<hyprland commit>",                        "<hyprtoplr commit>"]
    ["c4a4c341568944bd4fb9cd503558b2de602c0213", "1ab236602d66157a8c92662acbfcb6236df4f134"], # 0.50.0
    ["4e242d086e20b32951fdc0ebcbfb4d41b5be8dcc", "1ab236602d66157a8c92662acbfcb6236df4f134"], # 0.50.1
    ["46174f78b374b6cea669c48880877a8bdcf7802f", "1ab236602d66157a8c92662acbfcb6236df4f134"], # 0.51.0
    ["f56ec180d3a03a5aa978391249ff8f40f949fb73", "1ab236602d66157a8c92662acbfcb6236df4f134"], # 0.52.0
    ["ea444c35bb23b6e34505ab6753e069de7801cc25", "a4905de5f1a8dd9028d8df657ee0c0fe07852875"]  # 0.53.0
]

[hyprtoplr]
description = "Top Layer visibility plugin for Hyprland"
authors = ["subez"]
output = "hyprtoplr.so"
build = [
    "make all",
]
